### ISSUE TITLE
Caching not enabled

### ISSUE THREAD

**Issue by SeenaLibin** [apollographql/engine-docs#120]
Hi,
I have enabled caching and tracing in apollo engine. But i get only tracing details. A message **No cache policy was defined for this operation.**   is also shown

Here are my settings

> 
> const { ApolloEngine } = require('apollo-engine');
> const graphQLServer = express();
> graphQLServer.use('/graphql', bodyParser.json(), graphqlExpress(req => ({
>     tracing: true,
>     schema: schema,
>     context: req.headers,
>     graphiql: true,
>     cacheControl: true
> })));
> const engine = new ApolloEngine({ apiKey: 'myApiKey' });
> engine.listen({
>     port:8080,
>     expressApp: graphQLServer,
> });

Can you please tell me what I missed here to enable cache

**Comment by glasser** [comment]
Have you read the docs at https://www.apollographql.com/docs/engine/caching.html ?

You need to add cache control annotations to your schema or resolvers to tell Engine what can be cached and for how long.

**Comment by pablocarreraest** [comment]
is there documentation of using just apollo server cache without a framework?

I put in the apollo server: 
````typescript
const server: ApolloServer = new ApolloServer({
      schema,
      context: () => ({
        db: database,
      }),
      playground: {
        settings: {
          'editor.cursorShape': 'line',
          'editor.fontFamily': `-apple-system, BlinkMacSystemFont, 'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace`,
          'editor.theme': 'dark',
          'tracing.hideTracingResponse': false,
        },
      },
      tracing: true,
      cacheControl: true,
      engine: {
        apiKey: process.env.ENGINE_API_KEY,
      },

      // with key or false just don't work
      // engine: false,

      // Also with persisted queries I don't know how to use in client frontend with angular
      // persistedQueries: {
      //   cache: new RedisCache({
      //     host: process.env.REDIS_HOST,
      //     port: process.env.REDIS_PORT,
      //   }),
      // },
    });
````

I follow the documentation but have some problema.
