### ISSUE TITLE
Document how to transfer services from one account to another

### ISSUE THREAD

**Issue by zionts** [apollographql/engine-docs#177]
Hi! Yes your service is still on Engine and we can happily transfer it to your new Github organization for you. I looked in Engine and it looks like adam-team  isn't an account that hahs been set up yet on Engine. Can you go to this URL: https://engine.apollographql.com/?overlay=ManageAccounts and click the "Manage settings on Github" button so that Engine will be able to see your new adma-team  organization? Then if you click the "Refresh settings" button, Engine will be able to see your adam-team  organization and we can make the transfer for you!

--Dman

**Comment by daniman** [comment]
Done! https://www.apollographql.com/docs/engine/services.html#Transfering-a-service
