### ISSUE TITLE
Document that proxy strips variables in query string literal 

### ISSUE THREAD

**Issue by klairetan** [apollographql/engine-docs#182]
https://app.intercom.io/a/apps/lb30fyal/inbox/inbox/all/conversations/16451808459

Also recommend to not put variables in query string 

David Glasser: "The proxy has a "signature" algorithm which among other things replaces string literals in queries with the empty string. However we strongly advise that you keep this kind of sensitive data in variables if possible.

We send query strings in two formats to Engine. Signatures are calculated for every request that goes through and stats are reported on them. In addition we send full traces for a limited sample of queries. The full traces do contain the raw query without literal transformation, though I believe they are never actually shown in our UI. That's because the original motivation for doing signatures was so that users can consider queries that vary only on literals as the same, not for privacy/security reasons - it happens that it's also helpful for that, but that wasn't the original design reason. Of course it does somewhat undercut the incidental privacy/security benefits of taking signatures to also send full query strings. 

We are currently overhauling the engine reporting implementation to be more transparent and flexible. Until then the best I can say is that our recommendation is to not put private data directly in query strings; I understand that that's difficult for a public API."

**Comment by klairetan** [comment]
https://app.intercom.io/a/apps/lb30fyal/inbox/inbox/all/conversations/16493102719

The signature algorithm also replaces all "objects" (things like {foo: bar}) that are used in field arguments with {}.  Not to be a broken record but, yes, this is confusing and is why we're going to be moving away from this signature algorithm as soon as possible. Presumably your other variables were used in the object literals that are only showing up as {}.

**Comment by timbotnik** [comment]
Inspired by https://app.intercom.io/a/apps/lb30fyal/inbox/inbox/all/conversations/16648108729

We need to document what happens during "query normalization".

Possibly as part of https://www.apollographql.com/docs/engine/performance.html. Another idea: add a general feature like "query recording" that describes how Engine tracks your query usage, and can go into a bit of detail around what gets tracked (possibly move the data privacy section under here?).

**Comment by daniman** [comment]
Addressed by #186!
