### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/engine-docs#217]
Heads up that the link here… https://www.apollographql.com/docs/engine/setup-virtual.html#enable-apollo-tracing

…is a 404: https://www.apollographql.com/docs/engine/apollo-tracing.html

**Comment by ecker00** [comment]
Another broken link on https://www.apollographql.com/docs/engine/ which links to https://www.apollographql.com/engine/ (404)

**Comment by abernix** [comment]
Both of those links above are fixed.  Thank you, both of you!

**Comment by ecker00** [comment]
Awesome, that makes it easier! 👍 Reading the documentation for the first time it was a bit hard to understand what the "Apollo engine" was without doing some extra searches. Seems the terminology is a bit mixed and sometimes called the platform?
