### ISSUE TITLE
Improve protobuf docs page

### ISSUE THREAD

**Issue by stubailo** [apollographql/engine-docs#52]
https://www.apollographql.com/docs/engine/proto-doc.html

Improve formatting and add some guide sections. Looks like @zionts originally did the generation of those.

**Comment by stubailo** [comment]
And @thepwagner has been updating them.

**Comment by stubailo** [comment]
Unclear if it's best to have the auto-generated stuff at all.

**Comment by daniman** [comment]
Closing because we've made the changes that this ticket originally referred to. We can reopen or make a new ticket if necessary.
