### ISSUE TITLE
Can I use it with Apollo Client

### ISSUE THREAD

**Issue by marceloogeda** [apollographql/engine-docs#55]
There are great examples of how to use this with _apollo server_, but I'd like to know if it works with _apollo client_ if yes, how can I use it with?

**Comment by zionts** [comment]
@marceloogeda Engine is a tool specifically meant to give better insight into a GraphQL server. If you're not using Apollo Server, a [number of other servers](https://www.apollographql.com/docs/engine/apollo-tracing.html) are supported! I hope this helps to resolve your question :)

**Comment by marceloogeda** [comment]
Thank you @zionts
